
package bank.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddAccountSvcService", targetNamespace = "http://services.bank/", wsdlLocation = "http://localhost:8002/addAccount?wsdl")
public class AddAccountSvcService
    extends Service
{

    private final static URL ADDACCOUNTSVCSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDACCOUNTSVCSERVICE_EXCEPTION;
    private final static QName ADDACCOUNTSVCSERVICE_QNAME = new QName("http://services.bank/", "AddAccountSvcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/addAccount?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDACCOUNTSVCSERVICE_WSDL_LOCATION = url;
        ADDACCOUNTSVCSERVICE_EXCEPTION = e;
    }

    public AddAccountSvcService() {
        super(__getWsdlLocation(), ADDACCOUNTSVCSERVICE_QNAME);
    }

    public AddAccountSvcService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDACCOUNTSVCSERVICE_QNAME, features);
    }

    public AddAccountSvcService(URL wsdlLocation) {
        super(wsdlLocation, ADDACCOUNTSVCSERVICE_QNAME);
    }

    public AddAccountSvcService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDACCOUNTSVCSERVICE_QNAME, features);
    }

    public AddAccountSvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddAccountSvcService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddAccountSvc
     */
    @WebEndpoint(name = "AddAccountSvcPort")
    public AddAccountSvc getAddAccountSvcPort() {
        return super.getPort(new QName("http://services.bank/", "AddAccountSvcPort"), AddAccountSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddAccountSvc
     */
    @WebEndpoint(name = "AddAccountSvcPort")
    public AddAccountSvc getAddAccountSvcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.bank/", "AddAccountSvcPort"), AddAccountSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDACCOUNTSVCSERVICE_EXCEPTION!= null) {
            throw ADDACCOUNTSVCSERVICE_EXCEPTION;
        }
        return ADDACCOUNTSVCSERVICE_WSDL_LOCATION;
    }

}
