
package bank.services;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddAccountSvc", targetNamespace = "http://services.bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddAccountSvc {


    /**
     * 
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addBankAccount", targetNamespace = "http://services.bank/", className = "bank.services.AddBankAccount")
    @ResponseWrapper(localName = "addBankAccountResponse", targetNamespace = "http://services.bank/", className = "bank.services.AddBankAccountResponse")
    @Action(input = "http://services.bank/AddAccountSvc/addBankAccountRequest", output = "http://services.bank/AddAccountSvc/addBankAccountResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://services.bank/AddAccountSvc/addBankAccount/Fault/AuthorizationException")
    })
    public void addBankAccount()
        throws AuthorizationException_Exception
    ;

}
