
package bank.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankOperationSvcService", targetNamespace = "http://services.bank/", wsdlLocation = "http://localhost:8002/bankOperation?wsdl")
public class BankOperationSvcService
    extends Service
{

    private final static URL BANKOPERATIONSVCSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKOPERATIONSVCSERVICE_EXCEPTION;
    private final static QName BANKOPERATIONSVCSERVICE_QNAME = new QName("http://services.bank/", "BankOperationSvcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/bankOperation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKOPERATIONSVCSERVICE_WSDL_LOCATION = url;
        BANKOPERATIONSVCSERVICE_EXCEPTION = e;
    }

    public BankOperationSvcService() {
        super(__getWsdlLocation(), BANKOPERATIONSVCSERVICE_QNAME);
    }

    public BankOperationSvcService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKOPERATIONSVCSERVICE_QNAME, features);
    }

    public BankOperationSvcService(URL wsdlLocation) {
        super(wsdlLocation, BANKOPERATIONSVCSERVICE_QNAME);
    }

    public BankOperationSvcService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKOPERATIONSVCSERVICE_QNAME, features);
    }

    public BankOperationSvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankOperationSvcService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankOperationSvc
     */
    @WebEndpoint(name = "BankOperationSvcPort")
    public BankOperationSvc getBankOperationSvcPort() {
        return super.getPort(new QName("http://services.bank/", "BankOperationSvcPort"), BankOperationSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankOperationSvc
     */
    @WebEndpoint(name = "BankOperationSvcPort")
    public BankOperationSvc getBankOperationSvcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.bank/", "BankOperationSvcPort"), BankOperationSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKOPERATIONSVCSERVICE_EXCEPTION!= null) {
            throw BANKOPERATIONSVCSERVICE_EXCEPTION;
        }
        return BANKOPERATIONSVCSERVICE_WSDL_LOCATION;
    }

}
