
package bank.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeleteAccountSvc", targetNamespace = "http://services.bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeleteAccountSvc {


    /**
     * 
     * @param number
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBankAccount", targetNamespace = "http://services.bank/", className = "bank.services.DeleteBankAccount")
    @ResponseWrapper(localName = "deleteBankAccountResponse", targetNamespace = "http://services.bank/", className = "bank.services.DeleteBankAccountResponse")
    @Action(input = "http://services.bank/DeleteAccountSvc/deleteBankAccountRequest", output = "http://services.bank/DeleteAccountSvc/deleteBankAccountResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://services.bank/DeleteAccountSvc/deleteBankAccount/Fault/AuthorizationException")
    })
    public void deleteBankAccount(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws AuthorizationException_Exception
    ;

}
