
package bank.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAccountsSvcService", targetNamespace = "http://services.bank/", wsdlLocation = "http://localhost:8002/getAccounts?wsdl")
public class GetAccountsSvcService
    extends Service
{

    private final static URL GETACCOUNTSSVCSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETACCOUNTSSVCSERVICE_EXCEPTION;
    private final static QName GETACCOUNTSSVCSERVICE_QNAME = new QName("http://services.bank/", "GetAccountsSvcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/getAccounts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETACCOUNTSSVCSERVICE_WSDL_LOCATION = url;
        GETACCOUNTSSVCSERVICE_EXCEPTION = e;
    }

    public GetAccountsSvcService() {
        super(__getWsdlLocation(), GETACCOUNTSSVCSERVICE_QNAME);
    }

    public GetAccountsSvcService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETACCOUNTSSVCSERVICE_QNAME, features);
    }

    public GetAccountsSvcService(URL wsdlLocation) {
        super(wsdlLocation, GETACCOUNTSSVCSERVICE_QNAME);
    }

    public GetAccountsSvcService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETACCOUNTSSVCSERVICE_QNAME, features);
    }

    public GetAccountsSvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAccountsSvcService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAccountsSvc
     */
    @WebEndpoint(name = "GetAccountsSvcPort")
    public GetAccountsSvc getGetAccountsSvcPort() {
        return super.getPort(new QName("http://services.bank/", "GetAccountsSvcPort"), GetAccountsSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAccountsSvc
     */
    @WebEndpoint(name = "GetAccountsSvcPort")
    public GetAccountsSvc getGetAccountsSvcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.bank/", "GetAccountsSvcPort"), GetAccountsSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETACCOUNTSSVCSERVICE_EXCEPTION!= null) {
            throw GETACCOUNTSSVCSERVICE_EXCEPTION;
        }
        return GETACCOUNTSSVCSERVICE_WSDL_LOCATION;
    }

}
